### ISSUE TITLE
Feature Request: Directory upload.

### ISSUE THREAD

**Issue by AKPWebDesign** [jkcclemens/bins#5]
It'd be nice if I could upload a directory instead of a file, like so: `bins -s gist ./dir`

Also helpful would be a way to upload only certain types of files out of a directory and its subdirectories. Things like the following:

```
bins -s gist ./dir/*.js
bins -s gist ./dir/**/*.js
```

tl;dr: basically, glob support would be pretty cool.

**Comment by jkcclemens** [comment]
`bins` already supports globs (at least in zsh; I haven't tested elsewhere).

See [here](https://asciinema.org/a/7c04sqg1ohjuxhjdqnf8t8odq) for me using globs in my shell.

Otherwise, I won't introduce support for directories as arguments. Use globbing. Mistakes are too easy to make with directories!

**Comment by AKPWebDesign** [comment]
Fair enough. Thanks for the quick response!
